export const MODE_OPTIONS = [
  { value: 'ionian', label: 'Ionian (Major)' },
  { value: 'dorian', label: 'Dorian' },
  { value: 'phrygian', label: 'Phrygian' },
  { value: 'lydian', label: 'Lydian' },
  { value: 'mixolydian', label: 'Mixolydian' },
  { value: 'aeolian', label: 'Aeolian (Natural Minor)' },
  { value: 'locrian', label: 'Locrian' },
  { value: 'major pentatonic', label: 'Major Pentatonic' },
  { value: 'minor pentatonic', label: 'Minor Pentatonic' },
  { value: 'harmonic minor', label: 'Harmonic Minor' },
  { value: 'melodic minor', label: 'Melodic Minor' },
  { value: 'blues', label: 'Blues' },
  { value: 'whole tone', label: 'Whole Tone' },
  { value: 'diminished', label: 'Diminished' },
  { value: 'chromatic', label: 'Chromatic' },
  { value: 'custom', label: 'Custom' },
];

export const GENRE_OPTIONS = [
  { value: 'house', label: 'House' },
  { value: 'piano house', label: 'Piano House' },
  { value: 'deep house', label: 'Deep House' },
  { value: 'disco house', label: 'Disco House' },
  { value: 'tech house', label: 'Tech House' },
  { value: 'funk / disco', label: 'Funk / Disco' },
  { value: 'pop', label: 'Pop' },
  { value: 'indie pop', label: 'Indie Pop' },
  { value: 'r&b / neo soul', label: 'R&B / Neo Soul' },
  { value: 'jazz', label: 'Jazz' },
  { value: 'lo-fi', label: 'Lo-fi' },
  { value: 'ambient', label: 'Ambient' },
  { value: 'cinematic', label: 'Cinematic' },
  { value: 'edm', label: 'EDM' },
  { value: 'afro house', label: 'Afro House' },
  { value: 'progressive house', label: 'Progressive House' },
  { value: 'hip-hop', label: 'Hip-Hop' },
  { value: 'rock', label: 'Rock' },
  { value: 'folk', label: 'Folk' },
  { value: 'custom', label: 'Custom' },
];

export const CHORD_OPTIONS = [
  // Major chords
  'C',
  'D',
  'E',
  'F',
  'G',
  'A',
  'B',
  // Minor chords
  'Cm',
  'Dm',
  'Em',
  'Fm',
  'Gm',
  'Am',
  'Bm',
  // Seventh chords
  'C7',
  'D7',
  'E7',
  'F7',
  'G7',
  'A7',
  'B7',
  // Major seventh
  'Cmaj7',
  'Dmaj7',
  'Emaj7',
  'Fmaj7',
  'Gmaj7',
  'Amaj7',
  'Bmaj7',
  // Minor seventh
  'Cm7',
  'Dm7',
  'Em7',
  'Fm7',
  'Gm7',
  'Am7',
  'Bm7',
  // Other common extensions
  'Cadd9',
  'Dadd9',
  'Eadd9',
  'Fadd9',
  'Gadd9',
  'Aadd9',
  'Badd9',
  'Csus2',
  'Dsus2',
  'Esus2',
  'Fsus2',
  'Gsus2',
  'Asus2',
  'Bsus2',
  'Csus4',
  'Dsus4',
  'Esus4',
  'Fsus4',
  'Gsus4',
  'Asus4',
  'Bsus4',
  // Sharp chords
  'C#',
  'D#',
  'F#',
  'G#',
  'A#',
  'C#m',
  'D#m',
  'F#m',
  'G#m',
  'A#m',
  'C#maj7',
  'D#maj7',
  'F#maj7',
  'G#maj7',
  'A#maj7',
  'C#7',
  'D#7',
  'F#7',
  'G#7',
  'A#7',
  'C#m7',
  'D#m7',
  'F#m7',
  'G#m7',
  'A#m7',
  // Flat chords
  'Db',
  'Eb',
  'Gb',
  'Ab',
  'Bb',
  'Dbm',
  'Ebm',
  'Gbm',
  'Abm',
  'Bbm',
  'Dbmaj7',
  'Ebmaj7',
  'Gbmaj7',
  'Abmaj7',
  'Bbmaj7',
  'Db7',
  'Eb7',
  'Gb7',
  'Ab7',
  'Bb7',
  'Dbm7',
  'Ebm7',
  'Gbm7',
  'Abm7',
  'Bbm7',
];

export const MOOD_OPTIONS = [
  'Dreamy',
  'Dark',
  'Hopeful',
  'Energetic',
  'Melancholic',
  'Happy',
  'Sad',
  'Angry',
  'Calm',
  'Uplifting',
  'Emotional',
  'Peaceful',
  'Intense',
  'Mellow',
  'Bright',
  'Moody',
  'Somber',
  'Playful',
  'Dramatic',
  'Romantic',
  'Mysterious',
  'Ethereal',
  'Groovy',
  'Chill',
  'Epic',
  'Whimsical',
  'Nostalgic',
  'Vibrant',
  'Soulful',
  'Ambient',
  'Hypnotic',
  'Euphoric',
  'Melancholic',
  'Anxious',
  'Peaceful',
  'Triumphant',
  'Introspective',
  'Funky',
  'Ethereal',
  'Dark ambient',
  'Cinematic',
];
